---
- name: Deploying docker images
  hosts: localhost
  vars:
    DB_URL: "{{DB_URL}}"
    PORT: "{{PORT}}"
    SECRET_KEY: "{{SECRET_KEY}}"

  tasks:
    - name: Copy Docker Compose file from host machine to remote host
      copy:
        src: docker-compose.yml
        dest: ./

    - name: Pull docker image which is specified in docker compose
      shell:
        cmd: docker-compose pull
        chdir: ./

    - name: Running the docker images
      command: docker-compose up -d --build