---
- name: Deploy and Run Docker Containers
  hosts: localhost  
  become: yes

  tasks:
    - name: Pull Server Docker Image
      docker_image:
        name: laxmisreenivas/pixture-server:latest
        source: pull

    - name: Run Server Docker Container
      docker_container:
        name: pixture-server
        image: laxmisreenivas/pixture-server:latest
        state: started
        ports:
          - "5000:5000"
        env:
          - DB_URL=mongodb+srv://LaxmiGenius:HdvoWTWpZ6QaKewh@cluster0.zehgzrl.mongodb.net/?retryWrites=true&w=majority
          - PORT=5000
          - SECRET_KEY=shhh...

    - name: Pull Client Docker Image
      docker_image:
        name: laxmisreenivas/pixture-client:latest
        source: pull

    - name: Run Client Docker Container
      docker_container:
        name: pixture-client
        image: laxmisreenivas/pixture-client:latest
        state: started
        ports:
          - "3000:3000"

