---
- name: Deploy and Run Docker Containers
  hosts: localhost  
  tasks:
    - name: Pull Server image
      shell: docker pull laxmisreenivas/pixture-server:latest
    - name: Start docker service
      service:
        name: docker
        state: started
        ports:
          - "5000:5000"
        env:
          - DB_URL= {{DB_URL}}
          - PORT= {{PORT}}
          - SECRET_KEY= {{SECRET_KEY}}

    - name: Running container
      shell: docker run -d -p 5000:5000 laxmisreenivas/pixture-server:latest

   - name: Pull Client image
      shell: docker pull laxmisreenivas/pixture-client:latest
    - name: Start docker service
      service:
        name: docker
        state: started
        ports:
          - "3000:3000"
    - name: Running container
      shell: docker run -d -p 3000:3000 laxmisreenivas/pixture-client:latest

   
